[jobs.test0]
image = {source = "dockerfile", path = ".", tag = "golemc"}
run = [
  "python ./golemc.py $src -o $bin",
]
[jobs.golem1]
image = {source = "dockerfile", path = ".", tag = "golemc"}
run = [
  "python ./golemc.py $src -o $bin",
]
